### ISSUE TITLE
How to set the speed of dynamic obstacles?

### ISSUE THREAD

**Issue by sunnyhello3696** [Arena-Rosnav/arena-rosnav#173]
First of all, thank you very much to the developers, the latest version is great!
And then I'd like advice on how to adjust the speed of dynamic obstacles.
I now know how to set the number of randomly generated dynamic obstacles and the model, but I didn't find an interface to set the velocity
```
SCENARIO:
  file: default.json

PARAMETRIZED:
  file: default.xml 

STAGED:
  curriculum: "default.yaml"
  index: 0

RANDOM:
  # The seed parameter controls the random seed used for obstacle, robot start, and goal position generation. 
  # Providing a seed allows for stable reproduction of tasks. 
  # A value of -1 indicates a random seed will be used.
  seed: -1
  static:
    min: 5
    max: 10
    models: ["shelf"]
  interactive:
    min: 0
    max: 0
    models: ["shelf"]
  dynamic:
    min: 3
    max: 15
    models: ["actor1"]

```
