### ISSUE TITLE
Asking about custom robot's traning.

### ISSUE THREAD

**Issue by CAI23sbP** [Arena-Rosnav/arena-rosnav#41]
Hi @ReykCS. :>
i have two questions. first one is  `start_training.launch` and the other is `{$model}.model.yaml` &  'model_params.yaml'

1. `start_training.launch`
when i open `start_arena.launch`, it has task_mode (random, staged ,..). However in `start_training.launch` it has not that line.
i want to training agent in staged. could tell me how to do this?. is it a default value?

2. `{$model}.model.yaml` & `model_params.yaml `
this file path is `/src/utils/arena-simulation-setup/robot/{$model}/`.
i opened this file for setting to my robot, but i don't understand these lines.
 (1) in `{$model}.model.yaml` -> what is mean radius? is it wheel's radius?
```
bodies: # List of named bodies
  - name: base_footprint
    pose: [0, 0, 0]
    type: dynamic
    color: [0.2, 0.8, 0.2, 1.0]
    footprints:
      - type: circle
        radius: 0.105 # (0.105**2+0.041**2)**(1/2)
```
 (2) in  `model_params.yaml ` -> what are means that 'min', 'max', 'increment'?
```
laser:
  angle:
    min: 0
    max: 6.28318977356
    increment: 0.01745330492
```
could you tell me what they are talking to me?

P.s: There is any other to modify for using my robot before training?(I already modified costmaps)  and How long did you take about training for your agent?
Thank you!
